server:
  port: 9060

spring:
  application:
    name: event-handler
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        interceptor.classes: io.wisoft.eventsourcing.eventhandler.interceptor.KafkaProducerInterceptor

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${AXON_HOST:192.168.219.113}:8124

logging:
  level:
    io.wisoft.eventsourcing.event-handler: debug
    org.axonframework: debug
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.consumer.internals: WARN
    org.apache.kafka.common.config.internals: WARN
    org.apache.kafka.clients.Metadata: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"